[package]
name = "text-sanitizer"
version = "0.1.0"
authors = ["usr15"]
edition = "2018"

[dependencies]
sanitizer_lib = { path = "sanitizer-lib" }

[[example]]
name = "nut-monitor"

[build]
rustflags = [ "-C", "target-cpu=native" ]

[profile.release]
codegen-units = 1
lto = true
