[package]
name = "sanitizer_lib"
version = "1.0.0"
authors = ["Bodo Hugo Barwich <b.barwich@hotmail.com>"]
edition = "2018"

[lib]
name = "sanitizer_lib"
path = "src/sanitizer.rs"

[build]
rustflags = [ "-C", "target-cpu=native" ]

[profile.release]
codegen-units = 1
lto = true

