name: Publish new Release

# only trigger on pull request closed events
on:
  pull_request:
    types: 
      - closed
  workflow_dispatch:
    branches:    
      - master  

jobs:
  publish_release:
    # this job will only run if the PR has been merged
    if: (github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch') 
    runs-on: ubuntu-20.04
    # Docker Hub image that `publish_release` executes in
    # This will compile the release binary for Ubuntu Xenial
    container: ubuntu:xenial
    
    steps:
      - name: Check the Pull Request 
        if: github.event.pull_request != null 
        run: echo "Event '${{ github.event_name }}' - PR ${{ github.event.pull_request.number }} has been merged"
      
      - name: Check for Manual Launch 
        if: github.event_name == 'workflow_dispatch'
        run: echo "Event '${{ github.event_name }}' - Manual Push to Registry" 

      - name: Install Python Dependencies
        run: apt-get update && apt-get install python3-toml
      
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Cargo Version for text-sanitizer
        id: cargo_version
        run: |
          cargo_version=`scripts/cargo_version.py text-sanitizer | grep -i "text-sanitizer" | cut -d"=" -f2`
          if [ -z cargo_version ]; then echo "could not find CARGO VERSION"; exit 1; fi;
          version_tag="v$cargo_version"
          echo "version=$version_tag" >> $GITHUB_OUTPUT
          
      - name: Check Repository for Cargo Version Tag
        id: git_tag
        run: |
          git fetch --tags
          tag_label=`git tag -l "${{ steps.cargo_version.outputs.version }}"`
          if [ -z $tag_label ]; then tag_exists=0; else tag_exists=1; fi;
          echo "tag=$tag_label" >> $GITHUB_OUTPUT
          echo "exists=$tag_exists" >> $GITHUB_OUTPUT
        
      - name: Tag the Repository with Cargo Version Tag
        id: git_tag_set
        if: steps.git_tag.outputs.exists == 0
        run: |
          echo "git - tag: '${{ steps.git_tag.outputs.tag }}'; exists: '${{ steps.git_tag.outputs.exists }}'"
          git config user.email "42355798+bodo-hugo-barwich@users.noreply.github.com"
          git config user.name "Bodo Hugo Barwich"
          git tag -a "${{ steps.cargo_version.outputs.version }}" -m "text-sanitizer ${{ steps.cargo_version.outputs.version }} released"
          git push origin ${{ steps.cargo_version.outputs.version }}
          git checkout ${{ steps.cargo_version.outputs.version }}
          
      - name: Build Release Version
        id: build_release
        if: steps.git_tag.outputs.exists == 0
        run: | 
          cargo build --release --verbose 
          tar -C target/release/ -czf text-sanitizer_${{ steps.cargo_version.outputs.version }}.tar.gz text-sanitizer
          
      - name: Create Release
        id: release
        if: steps.git_tag.outputs.exists == 0
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.git_tag.outputs.tag }}
          token: ${{ secrets.PROJECT_RELEASE_TOKEN }}
          files: text-sanitizer_${{ steps.cargo_version.outputs.version }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_RELEASE_TOKEN }}       
                      
      - name: Crates.io Publish
        id: publish
        if: steps.git_tag.outputs.exists == 0
        run: |
          cd text-sanitizer
          cargo publish --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_PUBLISH_TOKEN }}       
          
        