name: Automated Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
     branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # This workflow contains a single job called "testing"
  testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - name: Profile Sanitizing 27KB Document
      run: time cat tests/data/lanzarote-com_de-ausfluge.html | target/debug/text-sanitizer -i en es de > lz_prof_result.html