name: Automated Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
     branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # This workflow contains a single job called "testing"
  testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
    - name: Build Release Version
      run: cargo build --release --verbose
    - name: Profile Sanitizing 27KB Document
      run: |
        start_time=`date +"%s.%N"` 
        time cat tests/data/lanzarote-com_de-ausfluge.html | target/release/text-sanitizer -i en es de > lz_prof_result.html
        end_time=`date +"%s.%N"`
        processing_time=`echo "scale=3; ${end_time}-${start_time}" | bc -l`
        echo "processing time: '$processing_time' s"